apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flaskapp
    name: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  strategy: {}
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
       - image: oyaro/flaskapp:latest
         name: flaskapp
         ports:
         - containerPort: 3000
         resources:
           requests:
            memory: "64Mi"
            cpu: "250m"
           limits:
            memory: "128Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: flaskapp-service
spec:
  ports:
  - nodePort: 30246
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskapp
  type: LoadBalancer


